const teamImages = {
    "Arizona Diamondbacks": "https://upload.wikimedia.org/wikipedia/en/8/89/Arizona_Diamondbacks_logo.svg",
    "Atlanta Braves": "https://upload.wikimedia.org/wikipedia/en/f/f2/Atlanta_Braves.svg",
    "Baltimore Orioles": "https://upload.wikimedia.org/wikipedia/en/7/75/Baltimore_Orioles_cap.svg",
    "Boston Red Sox": "https://upload.wikimedia.org/wikipedia/en/6/6d/RedSoxPrimary_HangingSocks.svg",
    "Chicago Cubs": "https://upload.wikimedia.org/wikipedia/commons/8/80/Chicago_Cubs_logo.svg",
    "Chicago White Sox": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Chicago_White_Sox.svg",
    "Cincinnati Reds": "https://upload.wikimedia.org/wikipedia/commons/0/01/Cincinnati_Reds_Logo.svg",
    "Cleveland Guardians": "https://upload.wikimedia.org/wikipedia/en/a/ae/Cleveland_Guardians_logo.svg",
    "Colorado Rockies": "https://upload.wikimedia.org/wikipedia/en/3/31/Colorado_Rockies_logo.svg",
    "Detroit Tigers": "https://upload.wikimedia.org/wikipedia/en/e/e3/Detroit_Tigers_logo.svg",
    "Houston Astros": "https://upload.wikimedia.org/wikipedia/en/6/6b/Houston_Astros_logo.svg",
    "Kansas City Royals": "https://upload.wikimedia.org/wikipedia/en/1/1c/Kansas_City_Royals.svg",
    "Los Angeles Angels": "https://upload.wikimedia.org/wikipedia/en/c/c0/Los_Angeles_Angels_of_Anaheim.svg",
    "Los Angeles Dodgers": "https://upload.wikimedia.org/wikipedia/en/6/63/Los_Angeles_Dodgers_logo.svg",
    "Miami Marlins": "https://upload.wikimedia.org/wikipedia/en/f/fd/Miami_Marlins_2020.svg",
    "Milwaukee Brewers": "https://upload.wikimedia.org/wikipedia/en/1/11/Milwaukee_Brewers_Logo.svg",
    "Minnesota Twins": "https://upload.wikimedia.org/wikipedia/en/b/b4/Minnesota_Twins_Insignia.svg",
    "New York Mets": "https://upload.wikimedia.org/wikipedia/en/7/7b/New_York_Mets.svg",
    "New York Yankees": "https://upload.wikimedia.org/wikipedia/en/2/25/NewYorkYankees_PrimaryLogo.svg",
    "Oakland Athletics": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Oakland_A%27s_logo.svg",
    "Philadelphia Phillies": "https://upload.wikimedia.org/wikipedia/en/f/f0/Philadelphia_Phillies_logo.svg",
    "Pittsburgh Pirates": "https://upload.wikimedia.org/wikipedia/en/6/6e/Pittsburgh_Pirates_logo.svg",
    "San Diego Padres": "https://upload.wikimedia.org/wikipedia/en/4/49/San_Diego_Padres_logo.svg",
    "San Francisco Giants": "https://upload.wikimedia.org/wikipedia/en/5/58/San_Francisco_Giants_Logo.svg",
    "Seattle Mariners": "https://upload.wikimedia.org/wikipedia/en/b/b0/Seattle_Mariners_logo.svg",
    "St. Louis Cardinals": "https://upload.wikimedia.org/wikipedia/en/4/45/StLouisCardinals_Logo.svg",
    "Tampa Bay Rays": "https://upload.wikimedia.org/wikipedia/en/a/a5/Tampa_Bay_Rays_logo.svg",
    "Texas Rangers": "https://upload.wikimedia.org/wikipedia/en/4/41/Texas_Rangers.svg",
    "Toronto Blue Jays": "https://upload.wikimedia.org/wikipedia/en/b/ba/Toronto_Blue_Jays_logo.svg",
    "Washington Nationals": "https://upload.wikimedia.org/wikipedia/en/a/a7/Washington_Nationals_logo.svg"
};
export default teamImages;
