const teamImages = {
    "Arizona Diamondbacks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/ari.png&h=150&w=150",
    "Atlanta Braves": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Atlanta_Braves.svg/150px-Atlanta_Braves.svg.png",
    "Baltimore Orioles": "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Baltimore_Orioles_cap.svg/150px-Baltimore_Orioles_cap.svg.png",
    "Boston Red Sox": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/RedSoxPrimary_HangingSocks.svg/150px-RedSoxPrimary_HangingSocks.svg.png",
    "Chicago Cubs": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Chicago_Cubs_logo.svg/150px-Chicago_Cubs_logo.svg.png",
    "Chicago White Sox": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Chicago_White_Sox.svg/150px-Chicago_White_Sox.svg.png",
    "Cincinnati Reds": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cincinnati_Reds_Logo.svg/150px-Cincinnati_Reds_Logo.svg.png",
    "Cleveland Guardians": "https://www.mlbstatic.com/team-logos/150x150/cleveland-guardians.png",
    "Colorado Rockies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/col.png&h=150&w=150",
    "Detroit Tigers": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Detroit_Tigers_logo.svg/150px-Detroit_Tigers_logo.svg.png",
    "Houston Astros": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/hou.png&h=150&w=150",
    "Kansas City Royals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/kc.png&h=150&w=150",
    "Los Angeles Angels": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/laa.png&h=150&w=150",
    "Los Angeles Dodgers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/lad.png&h=150&w=150",
    "Miami Marlins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mia.png&h=150&w=150",
    "Milwaukee Brewers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/mil.png&h=150&w=150",
    "Minnesota Twins": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/min.png&h=150&w=150",
    "New York Mets": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/New_York_Mets.svg/150px-New_York_Mets.svg.png",
    "New York Yankees": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/nyy.png&h=150&w=150",
    "Oakland Athletics": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Oakland_A%27s_logo.svg/150px-Oakland_A%27s_logo.svg.png",
    "Philadelphia Phillies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/phi.png&h=150&w=150",
    "Pittsburgh Pirates": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/pit.png&h=150&w=150",
    "San Diego Padres": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sd.png&h=150&w=150",
    "San Francisco Giants": "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/San_Francisco_Giants_Logo.svg/150px-San_Francisco_Giants_Logo.svg.png",
    "Seattle Mariners": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/sea.png&h=150&w=150",
    "St. Louis Cardinals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/stl.png&h=150&w=150",
    "Tampa Bay Rays": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/tb.png&h=150&w=150",
    "Texas Rangers": "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Texas_Rangers.svg/150px-Texas_Rangers.svg.png",
    "Toronto Blue Jays": "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Toronto_Blue_Jays_logo.svg/150px-Toronto_Blue_Jays_logo.svg.png",
    "Washington Nationals": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/mlb/500/wsh.png&h=150&w=150"
};

export default teamImages;
